### ISSUE TITLE
forest plots

### ISSUE THREAD

**Issue by softloud** [softloud/adpain#10]
- [x] embiggen
- [x] class in line segments #7 
- [x] direction of improvement 
- [ ] facet all in by condition (?)
- [ ] conditions in condition grouping #9 
- [x] fix calculation of point size #6 
- [x] titles dependent on all outcomes
- [x] x axis label
- [ ] increase difference between smallest and largest point sizes
- [ ] no. of trials, participants, studies
- [ ] I sq from pairwise
- [ ] add vlines for 0.2, 0.5, 0.8
- [ ] tau
- [ ] OR ref line & colours by 1

**Comment by softloud** [comment]
- [ ] total number of studies

**Comment by softloud** [comment]
pw forest

- study-level coef
- overall estimate
- size by weight??
- tau-sq, i-sq
- CIs & point estimates
- OR transformation & line of reference
- 0.2, etc. lines

**Comment by softloud** [comment]
Titles all commensurate with each other

**Comment by softloud** [comment]
Height by n obs

**Comment by softloud** [comment]
I^2

**Comment by softloud** [comment]
Remove guidelines for OR

**Comment by softloud** [comment]
- [ ] sort out ordering directions: need to be consistent across pw & nma
- [ ] pw generic (just the forest plot) & finesse (frequently changeable, titles, etc.)

**Comment by softloud** [comment]
- [ ] participants on nma
- [ ] same scale? 
- [ ] sample size?
