### ISSUE TITLE
pw pipeline one fig

### ISSUE THREAD

**Issue by softloud** [softloud/adpain#45]
## objective

Working pipeline for creation of one figure. 

## tasks

- [x] condition
- [ ] dose
- [x] debug forest: harder than I thought
- [ ] second axis
- [ ] tests for each step in the pipeline
- [ ] line sized by proportion of studies

## lor vs smd

- fixed x-axes
- conversion

## tests

- [x] expectations of get data
- [x] expectations of viable obs (via get data)
- [ ] expectations of meta pw table
- [x] mod dat as package data, then don't need to update test data
